/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function DemoScene1(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models/Demo_Scene_1.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Demo_Scene_1">
        <group name="Car_21A" position={[-46, 0.3, -5]} rotation={[0, 1.33, 0]}>
          <mesh
            name="Car_21A_1"
            castShadow
            receiveShadow
            geometry={nodes.Car_21A_1.geometry}
            material={materials.Car_21A_D}
          >
            <mesh
              name="Wheel_21A_FL"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_FL.geometry}
              material={materials.Car_21A_D}
              position={[1.26, 0.53, 4.61]}
            />
            <mesh
              name="Wheel_21A_FR"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_FR.geometry}
              material={materials.Car_21A_D}
              position={[-1.24, 0.53, 4.61]}
            />
            <mesh
              name="Wheel_21A_ML"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_ML.geometry}
              material={materials.Car_21A_D}
              position={[1.25, 0.53, 1.21]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              name="Wheel_21A_MR"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_MR.geometry}
              material={materials.Car_21A_D}
              position={[-1.25, 0.53, 1.21]}
            />
            <mesh
              name="Wheel_21A_RL"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_RL.geometry}
              material={materials.Car_21A_D}
              position={[1.25, 0.53, 0]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              name="Wheel_21A_RR"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_RR.geometry}
              material={materials.Car_21A_D}
              position={[-1.25, 0.53, 0]}
            />
          </mesh>
          <mesh
            name="Car_21A_Addon"
            castShadow
            receiveShadow
            geometry={nodes.Car_21A_Addon.geometry}
            material={materials.Car_21A_D}
            rotation={[0, -Math.PI / 6, 0]}
          >
            <mesh
              name="Car_21A_Addon_Wheel_FL"
              castShadow
              receiveShadow
              geometry={nodes.Car_21A_Addon_Wheel_FL.geometry}
              material={materials.Car_21A_D}
              position={[1.26, 0.55, -3]}
            />
            <mesh
              name="Car_21A_Addon_Wheel_FR"
              castShadow
              receiveShadow
              geometry={nodes.Car_21A_Addon_Wheel_FR.geometry}
              material={materials.Car_21A_D}
              position={[-1.24, 0.55, -3]}
            />
            <mesh
              name="Car_21A_Addon_Wheel_RL"
              castShadow
              receiveShadow
              geometry={nodes.Car_21A_Addon_Wheel_RL.geometry}
              material={materials.Car_21A_D}
              position={[1.26, 0.55, -4.2]}
            />
            <mesh
              name="Car_21A_Addon_Wheel_RR"
              castShadow
              receiveShadow
              geometry={nodes.Car_21A_Addon_Wheel_RR.geometry}
              material={materials.Car_21A_D}
              position={[-1.24, 0.55, -4.2]}
            />
          </mesh>
        </group>
        <group
          name="Car_21A_(2)"
          position={[-13.5, 0.1, -6]}
          rotation={[0, Math.PI / 2, 0]}
        >
          <mesh
            name="Car_21A_2"
            castShadow
            receiveShadow
            geometry={nodes.Car_21A_2.geometry}
            material={materials.Car_21A_D}
          >
            <mesh
              name="Wheel_21A_FL_1"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_FL_1.geometry}
              material={materials.Car_21A_D}
              position={[1.26, 0.53, 4.61]}
            />
            <mesh
              name="Wheel_21A_FR_1"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_FR_1.geometry}
              material={materials.Car_21A_D}
              position={[-1.24, 0.53, 4.61]}
            />
            <mesh
              name="Wheel_21A_ML_1"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_ML_1.geometry}
              material={materials.Car_21A_D}
              position={[1.25, 0.53, 1.21]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              name="Wheel_21A_MR_1"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_MR_1.geometry}
              material={materials.Car_21A_D}
              position={[-1.25, 0.53, 1.21]}
            />
            <mesh
              name="Wheel_21A_RL_1"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_RL_1.geometry}
              material={materials.Car_21A_D}
              position={[1.25, 0.53, 0]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              name="Wheel_21A_RR_1"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_RR_1.geometry}
              material={materials.Car_21A_D}
              position={[-1.25, 0.53, 0]}
            />
          </mesh>
        </group>
        <group
          name="Car_21A_(1)"
          position={[32.91, 0.3, -3.46]}
          rotation={[-Math.PI, 0.33, -Math.PI]}
        >
          <mesh
            name="Car_21A_3"
            castShadow
            receiveShadow
            geometry={nodes.Car_21A_3.geometry}
            material={materials.Car_21A_D}
          >
            <mesh
              name="Wheel_21A_FL_2"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_FL_2.geometry}
              material={materials.Car_21A_D}
              position={[1.26, 0.53, 4.61]}
              rotation={[0, Math.PI / 6, 0]}
            />
            <mesh
              name="Wheel_21A_FR_2"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_FR_2.geometry}
              material={materials.Car_21A_D}
              position={[-1.24, 0.53, 4.61]}
              rotation={[0, Math.PI / 6, 0]}
            />
            <mesh
              name="Wheel_21A_ML_2"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_ML_2.geometry}
              material={materials.Car_21A_D}
              position={[1.25, 0.53, 1.21]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              name="Wheel_21A_MR_2"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_MR_2.geometry}
              material={materials.Car_21A_D}
              position={[-1.25, 0.53, 1.21]}
            />
            <mesh
              name="Wheel_21A_RL_2"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_RL_2.geometry}
              material={materials.Car_21A_D}
              position={[1.25, 0.53, 0]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              name="Wheel_21A_RR_2"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_RR_2.geometry}
              material={materials.Car_21A_D}
              position={[-1.25, 0.53, 0]}
            />
          </mesh>
          <mesh
            name="Car_21A_Addon_1"
            castShadow
            receiveShadow
            geometry={nodes.Car_21A_Addon_1.geometry}
            material={materials.Car_21A_D}
            rotation={[0, -Math.PI / 6, 0]}
          >
            <mesh
              name="Car_21A_Addon_Wheel_FL_1"
              castShadow
              receiveShadow
              geometry={nodes.Car_21A_Addon_Wheel_FL_1.geometry}
              material={materials.Car_21A_D}
              position={[1.26, 0.55, -3]}
            />
            <mesh
              name="Car_21A_Addon_Wheel_FR_1"
              castShadow
              receiveShadow
              geometry={nodes.Car_21A_Addon_Wheel_FR_1.geometry}
              material={materials.Car_21A_D}
              position={[-1.24, 0.55, -3]}
            />
            <mesh
              name="Car_21A_Addon_Wheel_RL_1"
              castShadow
              receiveShadow
              geometry={nodes.Car_21A_Addon_Wheel_RL_1.geometry}
              material={materials.Car_21A_D}
              position={[1.26, 0.55, -4.2]}
            />
            <mesh
              name="Car_21A_Addon_Wheel_RR_1"
              castShadow
              receiveShadow
              geometry={nodes.Car_21A_Addon_Wheel_RR_1.geometry}
              material={materials.Car_21A_D}
              position={[-1.24, 0.55, -4.2]}
            />
          </mesh>
        </group>
        <group name="Car_21A_(3)" position={[49, 0.1, 10]}>
          <mesh
            name="Car_21A_4"
            castShadow
            receiveShadow
            geometry={nodes.Car_21A_4.geometry}
            material={materials.Car_21A_D}
          >
            <mesh
              name="Wheel_21A_FL_3"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_FL_3.geometry}
              material={materials.Car_21A_D}
              position={[1.26, 0.53, 4.61]}
            />
            <mesh
              name="Wheel_21A_FR_3"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_FR_3.geometry}
              material={materials.Car_21A_D}
              position={[-1.24, 0.53, 4.61]}
            />
            <mesh
              name="Wheel_21A_ML_3"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_ML_3.geometry}
              material={materials.Car_21A_D}
              position={[1.25, 0.53, 1.21]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              name="Wheel_21A_MR_3"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_MR_3.geometry}
              material={materials.Car_21A_D}
              position={[-1.25, 0.53, 1.21]}
            />
            <mesh
              name="Wheel_21A_RL_3"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_RL_3.geometry}
              material={materials.Car_21A_D}
              position={[1.25, 0.53, 0]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              name="Wheel_21A_RR_3"
              castShadow
              receiveShadow
              geometry={nodes.Wheel_21A_RR_3.geometry}
              material={materials.Car_21A_D}
              position={[-1.25, 0.53, 0]}
            />
          </mesh>
        </group>
        <mesh
          name="Tree_6C_(9)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6C_(9)"].geometry}
          material={materials.Tree_6A_D}
          position={[39.63, 0, -37.88]}
          rotation={[0, 0.6, 0]}
          scale={0.78}
        />
        <mesh
          name="Tree_6C_(5)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6C_(5)"].geometry}
          material={materials.Tree_6A_D}
          position={[-20.61, 0, 73.3]}
          rotation={[-Math.PI, 0.73, -Math.PI]}
        />
        <mesh
          name="Tree_6C_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6C_(3)"].geometry}
          material={materials.Tree_6A_D}
          position={[2.45, 0, 17.43]}
          rotation={[0, 1.3, 0]}
        />
        <mesh
          name="Tree_6C_(7)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6C_(7)"].geometry}
          material={materials.Tree_6A_D}
          position={[54.46, 0, 42.51]}
          rotation={[Math.PI, -1.47, Math.PI]}
        />
        <mesh
          name="Tree_6C"
          castShadow
          receiveShadow
          geometry={nodes.Tree_6C.geometry}
          material={materials.Tree_6A_D}
          position={[44.53, 0, 41.31]}
        />
        <mesh
          name="Tree_6C_(10)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6C_(10)"].geometry}
          material={materials.Tree_6A_D}
          position={[-59.16, 0, 28.98]}
          rotation={[0, 0.6, 0]}
          scale={0.78}
        />
        <mesh
          name="Tree_6C_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6C_(1)"].geometry}
          material={materials.Tree_6A_D}
          position={[22.62, 0, 63.39]}
          rotation={[Math.PI, -0.83, Math.PI]}
        />
        <mesh
          name="Tree_6C_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6C_(2)"].geometry}
          material={materials.Tree_6A_D}
          position={[-20.13, 0, 24.21]}
          rotation={[Math.PI, -0.83, Math.PI]}
        />
        <mesh
          name="Tree_6C_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6C_(4)"].geometry}
          material={materials.Tree_6A_D}
          position={[-71.7, 0, 4.3]}
          rotation={[-Math.PI, 0.73, -Math.PI]}
        />
        <mesh
          name="Tree_6C_(6)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6C_(6)"].geometry}
          material={materials.Tree_6A_D}
          position={[72.09, 0, 4.71]}
          rotation={[-Math.PI, 0.73, -Math.PI]}
        />
        <mesh
          name="Tree_6C_(8)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6C_(8)"].geometry}
          material={materials.Tree_6A_D}
          position={[40.77, 0, -16.14]}
          rotation={[Math.PI, -1.47, Math.PI]}
          scale={0.54}
        />
        <mesh
          name="Tree_6C_(12)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6C_(12)"].geometry}
          material={materials.Tree_6A_D}
          position={[-54, 0, -41.5]}
          rotation={[0, 0.6, 0]}
          scale={1.28}
        />
        <mesh
          name="Tree_6C_(13)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6C_(13)"].geometry}
          material={materials.Tree_6A_D}
          position={[64.1, 0, -28.5]}
          rotation={[0, 0.6, 0]}
          scale={1.28}
        />
        <mesh
          name="Tree_6D_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6D_(2)"].geometry}
          material={materials.Tree_6A_D}
          position={[-64.61, 0, -9.54]}
          rotation={[-Math.PI, 0.33, -Math.PI]}
          scale={1.58}
        />
        <mesh
          name="Tree_6D"
          castShadow
          receiveShadow
          geometry={nodes.Tree_6D.geometry}
          material={materials.Tree_6A_D}
          position={[29.24, 0, 42.83]}
        />
        <mesh
          name="Tree_6D_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6D_(1)"].geometry}
          material={materials.Tree_6A_D}
          position={[-59.19, 0, 2.03]}
          rotation={[0, -1.29, 0]}
        />
        <mesh
          name="Tree_6D_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6D_(3)"].geometry}
          material={materials.Tree_6A_D}
          position={[0.33, 0, -39.66]}
          rotation={[-Math.PI, 0.33, -Math.PI]}
          scale={1.92}
        />
        <mesh
          name="Tree_6D_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6D_(4)"].geometry}
          material={materials.Tree_6A_D}
          position={[88.25, 0, 0.37]}
          rotation={[0, 1.2, 0]}
          scale={1.92}
        />
        <mesh
          name="Tree_6D_(5)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6D_(5)"].geometry}
          material={materials.Tree_6A_D}
          position={[38.05, 0, 70.08]}
          rotation={[0, -0.24, 0]}
          scale={1.92}
        />
        <mesh
          name="Tree_6D_(6)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6D_(6)"].geometry}
          material={materials.Tree_6A_D}
          position={[85.7, 0, 31.1]}
          rotation={[-Math.PI, 1.53, -Math.PI]}
          scale={1.92}
        />
        <mesh
          name="Tree_6D_(7)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6D_(7)"].geometry}
          material={materials.Tree_6A_D}
          position={[-68.62, 0, 43.99]}
          rotation={[-Math.PI, 1.53, -Math.PI]}
          scale={1.92}
        />
        <mesh
          name="Tree_6A"
          castShadow
          receiveShadow
          geometry={nodes.Tree_6A.geometry}
          material={materials.Tree_6A_D}
          position={[-22, 0, 34]}
          rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
        />
        <mesh
          name="Tree_6A_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6A_(1)"].geometry}
          material={materials.Tree_6A_D}
          position={[-38, 0, 34]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Tree_6A_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6A_(2)"].geometry}
          material={materials.Tree_6A_D}
          position={[-44, 0, -16]}
          rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
        />
        <mesh
          name="Tree_6A_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_6A_(3)"].geometry}
          material={materials.Tree_6A_D}
          position={[18, 0, -22]}
          rotation={[0, -0.26, 0]}
        />
        <mesh
          name="Tree_6B"
          castShadow
          receiveShadow
          geometry={nodes.Tree_6B.geometry}
          material={materials.Tree_6A_D}
          position={[40, 0, 0]}
        />
        <mesh
          name="Trees_6A"
          castShadow
          receiveShadow
          geometry={nodes.Trees_6A.geometry}
          material={materials.Tree_6A_D}
          position={[-12, 0, 59]}
        />
        <mesh
          name="Pavement_2J_2X2_(14)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(14)"].geometry}
          material={materials.Road_1A_D}
          position={[-1, 0, 26]}
        />
        <mesh
          name="Pavement_2J_2X2_(18)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(18)"].geometry}
          material={materials.Road_1A_D}
          position={[69, 0, 4]}
        />
        <mesh
          name="Pavement_2J_2X2_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(4)"].geometry}
          material={materials.Road_1A_D}
          position={[10, 0, -29]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_2X2_(7)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(7)"].geometry}
          material={materials.Road_1A_D}
          position={[-39, 0, -13]}
        />
        <mesh
          name="Pavement_2J_2X2_(12)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(12)"].geometry}
          material={materials.Road_1A_D}
          position={[-3, 0, 3]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_2X2_(5)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(5)"].geometry}
          material={materials.Road_1A_D}
          position={[10, 0, -32]}
        />
        <mesh
          name="Pavement_2J_2X2_(9)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(9)"].geometry}
          material={materials.Road_1A_D}
          position={[-5, 0, 15]}
        />
        <mesh
          name="Pavement_2J_2X2_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(1)"].geometry}
          material={materials.Road_1A_D}
          position={[10, 0, -20]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_2X2_(13)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(13)"].geometry}
          material={materials.Road_1A_D}
          position={[-7, 0, 25]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_2X2_(19)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(19)"].geometry}
          material={materials.Road_1A_D}
          position={[-40, 0, 35]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_2X2_(16)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(16)"].geometry}
          material={materials.Road_1A_D}
          position={[0, 0, 24]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_2X2"
          castShadow
          receiveShadow
          geometry={nodes.Pavement_2J_2X2.geometry}
          material={materials.Road_1A_D}
          position={[10, 0, -17]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_2X2_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(2)"].geometry}
          material={materials.Road_1A_D}
          position={[10, 0, -23]}
        />
        <mesh
          name="Pavement_2J_2X2_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(3)"].geometry}
          material={materials.Road_1A_D}
          position={[10, 0, -26]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_2X2_(6)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(6)"].geometry}
          material={materials.Road_1A_D}
          position={[-37, 0, -13]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_2X2_(8)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(8)"].geometry}
          material={materials.Road_1A_D}
          position={[-41, 0, -13]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_2X2_(10)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(10)"].geometry}
          material={materials.Road_1A_D}
          position={[-6, 0, 11]}
        />
        <mesh
          name="Pavement_2J_2X2_(11)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(11)"].geometry}
          material={materials.Road_1A_D}
          position={[-5, 0, 13]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_2X2_(15)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(15)"].geometry}
          material={materials.Road_1A_D}
          position={[-4, 0, 11]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          name="Pavement_2J_2X2_(17)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(17)"].geometry}
          material={materials.Road_1A_D}
          position={[59, 0, 4]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_2X2_(20)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(20)"].geometry}
          material={materials.Road_1A_D}
          position={[-18, 0, 37]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_2X2_(21)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_2X2_(21)"].geometry}
          material={materials.Road_1A_D}
          position={[-15, 0, 37]}
        />
        <mesh
          name="Rock_Cluster_1A_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Rock_Cluster_1A_(1)"].geometry}
          material={materials.Road_1A_D}
          position={[65.7, 0, 4.2]}
          rotation={[Math.PI, -Math.PI / 4, Math.PI]}
        />
        <mesh
          name="Rock_Cluster_1A_(7)"
          castShadow
          receiveShadow
          geometry={nodes["Rock_Cluster_1A_(7)"].geometry}
          material={materials.Road_1A_D}
          position={[19.5, 0, 47.06]}
          rotation={[0, -1.25, 0]}
        />
        <mesh
          name="Rock_Cluster_1A_(5)"
          castShadow
          receiveShadow
          geometry={nodes["Rock_Cluster_1A_(5)"].geometry}
          material={materials.Road_1A_D}
          position={[-21.69, 0, -31.08]}
          rotation={[0, -1.25, 0]}
        />
        <mesh
          name="Rock_Cluster_1A_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Rock_Cluster_1A_(4)"].geometry}
          material={materials.Road_1A_D}
          position={[-18.58, 0, 2.12]}
          rotation={[0, -1.25, 0]}
        />
        <mesh
          name="Rock_Cluster_1A"
          castShadow
          receiveShadow
          geometry={nodes.Rock_Cluster_1A.geometry}
          material={materials.Road_1A_D}
          position={[2.48, 0, 13.13]}
          rotation={[Math.PI, -Math.PI / 4, Math.PI]}
        />
        <mesh
          name="Rock_Cluster_1A_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Rock_Cluster_1A_(3)"].geometry}
          material={materials.Road_1A_D}
          position={[-45.58, 0, -13.36]}
          rotation={[0, -1.25, 0]}
        />
        <mesh
          name="Rock_Cluster_1A_(6)"
          castShadow
          receiveShadow
          geometry={nodes["Rock_Cluster_1A_(6)"].geometry}
          material={materials.Road_1A_D}
          position={[66.81, 0, -25.13]}
          rotation={[0, -1.25, 0]}
        />
        <mesh
          name="Rock_Cluster_1A_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Rock_Cluster_1A_(2)"].geometry}
          material={materials.Road_1A_D}
          position={[-43.26, 0, 47.89]}
          rotation={[Math.PI, -Math.PI / 4, Math.PI]}
        />
        <mesh
          name="Road_1Z"
          castShadow
          receiveShadow
          geometry={nodes.Road_1Z.geometry}
          material={materials.Road_1A_D}
          position={[-30, 0, 28]}
        />
        <mesh
          name="Streetsign_3E"
          castShadow
          receiveShadow
          geometry={nodes.Streetsign_3E.geometry}
          material={materials.Road_1A_D}
          position={[1.1, 0.1, 57.01]}
          rotation={[-Math.PI, 1.33, -Math.PI]}
        />
        <mesh
          name="Streetsign_3E_(8)"
          castShadow
          receiveShadow
          geometry={nodes["Streetsign_3E_(8)"].geometry}
          material={materials.Road_1A_D}
          position={[56.95, 0.3, 8.59]}
          rotation={[0, -1.39, 0]}
        />
        <mesh
          name="Streetsign_3E_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Streetsign_3E_(1)"].geometry}
          material={materials.Road_1A_D}
          position={[0.91, 0.1, 61.11]}
          rotation={[0, 1.36, 0]}
        />
        <mesh
          name="Streetsign_3E_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Streetsign_3E_(4)"].geometry}
          material={materials.Road_1A_D}
          position={[-39.22, 0.3, 25.99]}
          rotation={[-Math.PI, 1.16, -Math.PI]}
        />
        <mesh
          name="Streetsign_3E_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Streetsign_3E_(2)"].geometry}
          material={materials.Road_1A_D}
          position={[-39.42, 0.3, 30.86]}
          rotation={[-Math.PI, 1.25, -Math.PI]}
        />
        <mesh
          name="Streetsign_3E_(5)"
          castShadow
          receiveShadow
          geometry={nodes["Streetsign_3E_(5)"].geometry}
          material={materials.Road_1A_D}
          position={[56.93, 0.3, 15.92]}
          rotation={[Math.PI, -1.3, Math.PI]}
        />
        <mesh
          name="Streetsign_3E_(7)"
          castShadow
          receiveShadow
          geometry={nodes["Streetsign_3E_(7)"].geometry}
          material={materials.Road_1A_D}
          position={[57.23, 0.3, 11.64]}
          rotation={[Math.PI, -1.31, Math.PI]}
        />
        <mesh
          name="Streetsign_3E_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Streetsign_3E_(3)"].geometry}
          material={materials.Road_1A_D}
          position={[-39.23, 0.3, 23.73]}
          rotation={[0, 1.34, 0]}
        />
        <mesh
          name="Streetsign_3E_(6)"
          castShadow
          receiveShadow
          geometry={nodes["Streetsign_3E_(6)"].geometry}
          material={materials.Road_1A_D}
          position={[57.1, 0.3, 13.75]}
          rotation={[0, -1.53, 0]}
        />
        <mesh
          name="Barrel_1G_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Barrel_1G_(3)"].geometry}
          material={materials.Road_1A_D}
          position={[58.11, 1.55, 17.17]}
          rotation={[0, 0.66, 0]}
        />
        <mesh
          name="Barrel_1G_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Barrel_1G_(2)"].geometry}
          material={materials.Road_1A_D}
          position={[57.05, 0.3, 17.82]}
          rotation={[0, 0.66, 0]}
        />
        <mesh
          name="Barrel_1G"
          castShadow
          receiveShadow
          geometry={nodes.Barrel_1G.geometry}
          material={materials.Road_1A_D}
          position={[-41.77, 0.3, 24.93]}
        />
        <mesh
          name="Barrel_1G_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Barrel_1G_(1)"].geometry}
          material={materials.Road_1A_D}
          position={[14.02, 0.3, -16.17]}
        />
        <mesh
          name="Rock_Cluster_1B_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Rock_Cluster_1B_(1)"].geometry}
          material={materials.Road_1A_D}
          position={[-8.58, 0, 46.53]}
          rotation={[Math.PI, -1.31, Math.PI]}
        />
        <mesh
          name="Rock_Cluster_1B_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Rock_Cluster_1B_(4)"].geometry}
          material={materials.Road_1A_D}
          position={[-18.9, 0, -41.2]}
          rotation={[Math.PI, -1.34, Math.PI]}
        />
        <mesh
          name="Rock_Cluster_1B_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Rock_Cluster_1B_(3)"].geometry}
          material={materials.Road_1A_D}
          position={[41.99, 0, 3.9]}
          rotation={[Math.PI, -1.34, Math.PI]}
        />
        <mesh
          name="Rock_Cluster_1B"
          castShadow
          receiveShadow
          geometry={nodes.Rock_Cluster_1B.geometry}
          material={materials.Road_1A_D}
          position={[40.52, 0, 34.58]}
          rotation={[Math.PI, -1.31, Math.PI]}
        />
        <mesh
          name="Rock_Cluster_1B_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Rock_Cluster_1B_(2)"].geometry}
          material={materials.Road_1A_D}
          position={[-14.09, 0, 4.82]}
          rotation={[0, -0.88, 0]}
        />
        <mesh
          name="Pavement_2J_4X4_(10)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_4X4_(10)"].geometry}
          material={materials.Road_1A_D}
          position={[-38, 0, 24]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_4X4"
          castShadow
          receiveShadow
          geometry={nodes.Pavement_2J_4X4.geometry}
          material={materials.Road_1A_D}
          position={[-6, 0, 4]}
        />
        <mesh
          name="Pavement_2J_4X4_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_4X4_(1)"].geometry}
          material={materials.Road_1A_D}
          position={[-4, 0, 8]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_4X4_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_4X4_(4)"].geometry}
          material={materials.Road_1A_D}
          position={[-8, 0, 14]}
        />
        <mesh
          name="Pavement_2J_4X4_(9)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_4X4_(9)"].geometry}
          material={materials.Road_1A_D}
          position={[-42, 0, 32]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_4X4_(6)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_4X4_(6)"].geometry}
          material={materials.Road_1A_D}
          position={[-5, 0, 30]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_4X4_(5)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_4X4_(5)"].geometry}
          material={materials.Road_1A_D}
          position={[-4, 0, 26]}
        />
        <mesh
          name="Pavement_2J_4X4_(11)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_4X4_(11)"].geometry}
          material={materials.Road_1A_D}
          position={[-38, 0, 28]}
        />
        <mesh
          name="Pavement_2J_4X4_(7)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_4X4_(7)"].geometry}
          material={materials.Road_1A_D}
          position={[-42, 0, 24]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          name="Pavement_2J_4X4_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_4X4_(2)"].geometry}
          material={materials.Road_1A_D}
          position={[-6, 0, 18]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_4X4_(8)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_4X4_(8)"].geometry}
          material={materials.Road_1A_D}
          position={[-42, 0, 28]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_2J_4X4_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_4X4_(3)"].geometry}
          material={materials.Road_1A_D}
          position={[-5, 0, 22]}
        />
        <mesh
          name="Pavement_2J_4X4_(12)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_2J_4X4_(12)"].geometry}
          material={materials.Road_1A_D}
          position={[-38, 0, 32]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Parking_1B_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Parking_1B_(1)"].geometry}
          material={materials.Road_1A_D}
          position={[6, 0, 38]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Parking_1B"
          castShadow
          receiveShadow
          geometry={nodes.Parking_1B.geometry}
          material={materials.Road_1A_D}
          position={[26, 0, 18]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          name="Barrel_1F"
          castShadow
          receiveShadow
          geometry={nodes.Barrel_1F.geometry}
          material={materials.Road_1A_D}
          position={[-42.95, 0.3, 24.26]}
          rotation={[Math.PI, -Math.PI / 3, Math.PI]}
        />
        <mesh
          name="Barrel_1F_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Barrel_1F_(2)"].geometry}
          material={materials.Road_1A_D}
          position={[57.48, 0.3, 16.36]}
          rotation={[-Math.PI, 0.33, -Math.PI]}
        />
        <mesh
          name="Barrel_1F_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Barrel_1F_(4)"].geometry}
          material={materials.Road_1A_D}
          position={[57.65, 0.3, 17.14]}
          rotation={[0, -1.49, 0]}
        />
        <mesh
          name="Barrel_1F_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Barrel_1F_(3)"].geometry}
          material={materials.Road_1A_D}
          position={[58.48, 0.3, 17.3]}
          rotation={[0, 1.08, 0]}
        />
        <mesh
          name="Barrel_1F_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Barrel_1F_(1)"].geometry}
          material={materials.Road_1A_D}
          position={[-42.51, 0.3, 26.12]}
          rotation={[0, -0.7, 0]}
        />
        <mesh
          name="Pavement_Special_1A_12X12_(7)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_Special_1A_12X12_(7)"].geometry}
          material={materials.Road_1A_D}
          position={[-42, 0, -6]}
        />
        <mesh
          name="Pavement_Special_1A_12X12_(9)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_Special_1A_12X12_(9)"].geometry}
          material={materials.Road_1A_D}
          position={[-50, 0, 28]}
        />
        <mesh
          name="Pavement_Special_1A_12X12_(6)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_Special_1A_12X12_(6)"].geometry}
          material={materials.Road_1A_D}
          position={[64, 0, 24]}
        />
        <mesh
          name="Pavement_Special_1A_12X12_(5)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_Special_1A_12X12_(5)"].geometry}
          material={materials.Road_1A_D}
          position={[76, 0, 24]}
        />
        <mesh
          name="Pavement_Special_1A_12X12_(8)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_Special_1A_12X12_(8)"].geometry}
          material={materials.Road_1A_D}
          position={[-54, 0, -6]}
        />
        <mesh
          name="Roundabout_2D"
          castShadow
          receiveShadow
          geometry={nodes.Roundabout_2D.geometry}
          material={materials.Road_1A_D}
          position={[26, 0, -8]}
        >
          <mesh
            name="Roundabout_2D_Rotating_Text"
            castShadow
            receiveShadow
            geometry={nodes.Roundabout_2D_Rotating_Text.geometry}
            material={materials.Road_1A_D}
          />
        </mesh>
        <mesh
          name="Streetlight_1C_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Streetlight_1C_(2)"].geometry}
          material={materials.Road_1A_D}
          position={[-31, 0, -10]}
          rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
        >
          <group
            name="Cube"
            position={[-1.29, 7.42, 0]}
            rotation={[0, 0, Math.PI / 3]}
            scale={[0.3, 3.42, 0.3]}
          />
        </mesh>
        <mesh
          name="Streetlight_1C_(7)"
          castShadow
          receiveShadow
          geometry={nodes["Streetlight_1C_(7)"].geometry}
          material={materials.Road_1A_D}
          position={[21, 0, 29]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <group
            name="Cube_1"
            position={[-1.29, 7.42, 0]}
            rotation={[0, 0, Math.PI / 3]}
            scale={[0.3, 3.42, 0.3]}
          />
        </mesh>
        <mesh
          name="Streetlight_1C_(8)"
          castShadow
          receiveShadow
          geometry={nodes["Streetlight_1C_(8)"].geometry}
          material={materials.Road_1A_D}
          position={[17, 0, 33]}
          rotation={[0, Math.PI / 2, 0]}
        >
          <group
            name="Cube_2"
            position={[-1.29, 7.42, 0]}
            rotation={[0, 0, Math.PI / 3]}
            scale={[0.3, 3.42, 0.3]}
          />
        </mesh>
        <mesh
          name="Streetlight_1C_(5)"
          castShadow
          receiveShadow
          geometry={nodes["Streetlight_1C_(5)"].geometry}
          material={materials.Road_1A_D}
          position={[32, 0, 6]}
          rotation={[0, Math.PI / 2, 0]}
        >
          <group
            name="Cube_3"
            position={[-1.29, 7.42, 0]}
            rotation={[0, 0, Math.PI / 3]}
            scale={[0.3, 3.42, 0.3]}
          />
        </mesh>
        <mesh
          name="Streetlight_1C_(9)"
          castShadow
          receiveShadow
          geometry={nodes["Streetlight_1C_(9)"].geometry}
          material={materials.Road_1A_D}
          position={[19, 0, 45]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <group
            name="Cube_4"
            position={[-1.29, 7.42, 0]}
            rotation={[0, 0, Math.PI / 3]}
            scale={[0.3, 3.42, 0.3]}
          />
        </mesh>
        <mesh
          name="Streetlight_1C_(6)"
          castShadow
          receiveShadow
          geometry={nodes["Streetlight_1C_(6)"].geometry}
          material={materials.Road_1A_D}
          position={[32, 0, 29]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <group
            name="Cube_5"
            position={[-1.29, 7.42, 0]}
            rotation={[0, 0, Math.PI / 3]}
            scale={[0.3, 3.42, 0.3]}
          />
        </mesh>
        <mesh
          name="Streetlight_1C"
          castShadow
          receiveShadow
          geometry={nodes.Streetlight_1C.geometry}
          material={materials.Road_1A_D}
          position={[-25, 0, 2]}
        >
          <group
            name="Cube_6"
            position={[-1.29, 7.42, 0]}
            rotation={[0, 0, Math.PI / 3]}
            scale={[0.3, 3.42, 0.3]}
          />
        </mesh>
        <mesh
          name="Streetlight_1C_(10)"
          castShadow
          receiveShadow
          geometry={nodes["Streetlight_1C_(10)"].geometry}
          material={materials.Road_1A_D}
          position={[-7, 0, 45]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <group
            name="Cube_7"
            position={[-1.29, 7.42, 0]}
            rotation={[0, 0, Math.PI / 3]}
            scale={[0.3, 3.42, 0.3]}
          />
        </mesh>
        <mesh
          name="Streetlight_1C_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Streetlight_1C_(1)"].geometry}
          material={materials.Road_1A_D}
          position={[-20, 0, -3]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <group
            name="Cube_8"
            position={[-1.29, 7.42, 0]}
            rotation={[0, 0, Math.PI / 3]}
            scale={[0.3, 3.42, 0.3]}
          />
        </mesh>
        <mesh
          name="Streetlight_1C_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Streetlight_1C_(3)"].geometry}
          material={materials.Road_1A_D}
          position={[11, 0, -3]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <group
            name="Cube_9"
            position={[-1.29, 7.42, 0]}
            rotation={[0, 0, Math.PI / 3]}
            scale={[0.3, 3.42, 0.3]}
          />
        </mesh>
        <mesh
          name="Streetlight_1C_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Streetlight_1C_(4)"].geometry}
          material={materials.Road_1A_D}
          position={[21, 0, 7]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <group
            name="Cube_10"
            position={[-1.29, 7.42, 0]}
            rotation={[0, 0, Math.PI / 3]}
            scale={[0.3, 3.42, 0.3]}
          />
        </mesh>
        <mesh
          name="Streetsign_3D_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Streetsign_3D_(2)"].geometry}
          material={materials.Road_1A_D}
          position={[-25.42, 0.1, 37.05]}
          rotation={[0, -0.7, 0]}
        />
        <mesh
          name="Streetsign_3D_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Streetsign_3D_(1)"].geometry}
          material={materials.Road_1A_D}
          position={[-5.23, 0.1, 39.84]}
          rotation={[-Math.PI, 0.92, -Math.PI]}
        />
        <mesh
          name="Streetsign_3D"
          castShadow
          receiveShadow
          geometry={nodes.Streetsign_3D.geometry}
          material={materials.Road_1A_D}
          position={[21.69, 0, -33.91]}
          rotation={[0, 0.51, 0]}
        />
        <mesh
          name="Rock_Cluster_1C_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Rock_Cluster_1C_(3)"].geometry}
          material={materials.Road_1A_D}
          position={[39.3, 0, -33.2]}
          rotation={[Math.PI, -1.45, Math.PI]}
        />
        <mesh
          name="Rock_Cluster_1C_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Rock_Cluster_1C_(4)"].geometry}
          material={materials.Road_1A_D}
          position={[50.13, 0, 32.36]}
          rotation={[Math.PI, -1.45, Math.PI]}
        />
        <mesh
          name="Rock_Cluster_1C_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Rock_Cluster_1C_(1)"].geometry}
          material={materials.Road_1A_D}
          position={[-15.8, 0, 33.91]}
          rotation={[0, 0.09, 0]}
        />
        <mesh
          name="Rock_Cluster_1C"
          castShadow
          receiveShadow
          geometry={nodes.Rock_Cluster_1C.geometry}
          material={materials.Road_1A_D}
          position={[-1.02, 0, 16.57]}
          rotation={[0, 0.09, 0]}
        />
        <mesh
          name="Rock_Cluster_1C_(5)"
          castShadow
          receiveShadow
          geometry={nodes["Rock_Cluster_1C_(5)"].geometry}
          material={materials.Road_1A_D}
          position={[61.74, 0, 46.94]}
          rotation={[Math.PI, -1.45, Math.PI]}
        />
        <mesh
          name="Rock_Cluster_1C_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Rock_Cluster_1C_(2)"].geometry}
          material={materials.Road_1A_D}
          position={[-57.67, 0, 22.76]}
          rotation={[0, 0.09, 0]}
        />
        <mesh
          name="Pavement_Rounded_2E_8X8"
          castShadow
          receiveShadow
          geometry={nodes.Pavement_Rounded_2E_8X8.geometry}
          material={materials.Road_1A_D}
          position={[12, 0, -22]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Pavement_Rounded_2E_8X8_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_Rounded_2E_8X8_(1)"].geometry}
          material={materials.Road_1A_D}
          position={[40, 0, -22]}
        />
        <mesh
          name="Pavement_Rounded_2E_8X8_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Pavement_Rounded_2E_8X8_(2)"].geometry}
          material={materials.Road_1A_D}
          position={[40, 0, 6]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Road_3X"
          castShadow
          receiveShadow
          geometry={nodes.Road_3X.geometry}
          material={materials.Road_1A_D}
          position={[26, 0, 38]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Bilboard_1E"
          castShadow
          receiveShadow
          geometry={nodes.Bilboard_1E.geometry}
          material={materials.Road_1A_D}
          position={[-11, 0, 0]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="Bilboard_1E_Rotating_Text"
            castShadow
            receiveShadow
            geometry={nodes.Bilboard_1E_Rotating_Text.geometry}
            material={materials.Road_1A_D}
          />
        </mesh>
        <mesh
          name="Streetsign_2J_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Streetsign_2J_(1)"].geometry}
          material={materials.Road_1A_D}
          position={[-5, 0, 43]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Streetsign_2J_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Streetsign_2J_(2)"].geometry}
          material={materials.Road_1A_D}
          position={[18, 0, 33]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Streetsign_2J"
          castShadow
          receiveShadow
          geometry={nodes.Streetsign_2J.geometry}
          material={materials.Road_1A_D}
          position={[31, 0, 32]}
        />
        <mesh
          name="Road_3W"
          castShadow
          receiveShadow
          geometry={nodes.Road_3W.geometry}
          material={materials.Road_1A_D}
          position={[-6, 0, 38]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Road_3W_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Road_3W_(1)"].geometry}
          material={materials.Road_1A_D}
          position={[82, 0, 12]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          name="Road_3Y"
          castShadow
          receiveShadow
          geometry={nodes.Road_3Y.geometry}
          material={materials.Road_1A_D}
          position={[-30, 0, -8]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="Road_1A_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Road_1A_(1)"].geometry}
          material={materials.Road_1A_D}
          position={[76, 0, 12]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Road_1A"
          castShadow
          receiveShadow
          geometry={nodes.Road_1A.geometry}
          material={materials.Road_1A_D}
          position={[64, 0, 12]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Tree_7A_(5)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7A_(5)"].geometry}
          material={materials.Tree_7A_D}
          position={[82.5, 0, -7.1]}
          rotation={[0, 0.79, 0]}
          scale={1.66}
        />
        <mesh
          name="Tree_7A_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7A_(1)"].geometry}
          material={materials.Tree_7A_D}
          position={[12, 0, 6]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Tree_7A"
          castShadow
          receiveShadow
          geometry={nodes.Tree_7A.geometry}
          material={materials.Tree_7A_D}
          position={[4.5, 0, 25.5]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Tree_7A_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7A_(2)"].geometry}
          material={materials.Tree_7A_D}
          position={[48.14, 0, -51.56]}
          rotation={[0, -0.4, 0]}
          scale={1.3}
        />
        <mesh
          name="Tree_7A_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7A_(3)"].geometry}
          material={materials.Tree_7A_D}
          position={[50.3, 0, 66.8]}
          rotation={[0, -0.4, 0]}
          scale={1.66}
        />
        <mesh
          name="Tree_7A_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7A_(4)"].geometry}
          material={materials.Tree_7A_D}
          position={[-74.1, 0, 29.8]}
          rotation={[0, -0.4, 0]}
          scale={1.66}
        />
        <mesh
          name="Tree_7D_(5)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7D_(5)"].geometry}
          material={materials.Tree_7A_D}
          position={[38.4, 0, -24.5]}
          rotation={[0, 0.51, 0]}
          scale={1.15}
        />
        <mesh
          name="Tree_7D"
          castShadow
          receiveShadow
          geometry={nodes.Tree_7D.geometry}
          material={materials.Tree_7A_D}
          position={[-12.05, 0, 28.37]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Tree_7D_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7D_(1)"].geometry}
          material={materials.Tree_7A_D}
          position={[51.8, 0, 4.2]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Tree_7D_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7D_(2)"].geometry}
          material={materials.Tree_7A_D}
          position={[45.7, 0, 32]}
          rotation={[0, -0.19, 0]}
          scale={1.41}
        />
        <mesh
          name="Tree_7D_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7D_(3)"].geometry}
          material={materials.Tree_7A_D}
          position={[79.9, 0, 2.3]}
          rotation={[-Math.PI, 0.55, -Math.PI]}
          scale={1.41}
        />
        <mesh
          name="Tree_7D_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7D_(4)"].geometry}
          material={materials.Tree_7A_D}
          position={[21.1, 0, 57.3]}
          rotation={[0, 0.51, 0]}
          scale={1.67}
        />
        <mesh
          name="Tree_7D_(6)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7D_(6)"].geometry}
          material={materials.Tree_7A_D}
          position={[-60.8, 0, -16.8]}
          rotation={[-Math.PI, 0.63, -Math.PI]}
          scale={1.65}
        />
        <mesh
          name="Tree_7D_(7)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7D_(7)"].geometry}
          material={materials.Tree_7A_D}
          position={[-74.5, 0, 15.8]}
          rotation={[-Math.PI, -0.77, -Math.PI]}
          scale={2.03}
        />
        <mesh
          name="Tree_7B_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7B_(2)"].geometry}
          material={materials.Tree_7A_D}
          position={[38.91, 0, 45.55]}
          rotation={[-Math.PI, 1.51, -Math.PI]}
          scale={1.01}
        />
        <mesh
          name="Tree_7B"
          castShadow
          receiveShadow
          geometry={nodes.Tree_7B.geometry}
          material={materials.Tree_7A_D}
          position={[-8.5, 0, 10.45]}
          rotation={[0, 0.26, 0]}
        />
        <mesh
          name="Tree_7B_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7B_(1)"].geometry}
          material={materials.Tree_7A_D}
          position={[-15.96, 0, 41.11]}
          rotation={[-Math.PI, 0.91, -Math.PI]}
          scale={1.13}
        />
        <mesh
          name="Tree_7B_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7B_(3)"].geometry}
          material={materials.Tree_7A_D}
          position={[-5.52, 0, 72.73]}
          rotation={[0, 1.22, 0]}
          scale={1.23}
        />
        <mesh
          name="Tree_7B_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7B_(4)"].geometry}
          material={materials.Tree_7A_D}
          position={[56.45, 0, -24.99]}
          rotation={[0, -0.56, 0]}
          scale={1.23}
        />
        <mesh
          name="Tree_7B_(5)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7B_(5)"].geometry}
          material={materials.Tree_7A_D}
          position={[-26.99, 0, -38.54]}
          rotation={[0, 0.6, 0]}
          scale={1.23}
        />
        <mesh
          name="Tree_7B_(6)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7B_(6)"].geometry}
          material={materials.Tree_7A_D}
          position={[-72.2, 0, -10.3]}
          rotation={[0, 0.6, 0]}
          scale={1.23}
        />
        <mesh
          name="Tree_7B_(7)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7B_(7)"].geometry}
          material={materials.Tree_7A_D}
          position={[68.2, 0, 39.2]}
          rotation={[-Math.PI, 0.51, -Math.PI]}
          scale={1.23}
        />
        <mesh
          name="Tree_7B_(8)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7B_(8)"].geometry}
          material={materials.Tree_7A_D}
          position={[13.74, 0, 73.02]}
          rotation={[-Math.PI, 0.51, -Math.PI]}
          scale={1.23}
        />
        <mesh
          name="Tree_7B_(9)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7B_(9)"].geometry}
          material={materials.Tree_7A_D}
          position={[-45.37, 0, 53.19]}
          rotation={[0, 0.78, 0]}
          scale={1.68}
        />
        <mesh
          name="Tree_7F_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7F_(1)"].geometry}
          material={materials.Tree_7A_D}
          position={[89.5, 0, 39.6]}
          rotation={[Math.PI, -1.18, Math.PI]}
        />
        <mesh
          name="Tree_7F_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7F_(3)"].geometry}
          material={materials.Tree_7A_D}
          position={[-66.8, 0, -25.9]}
          rotation={[Math.PI, -1.18, Math.PI]}
          scale={1.34}
        />
        <mesh
          name="Tree_7F"
          castShadow
          receiveShadow
          geometry={nodes.Tree_7F.geometry}
          material={materials.Tree_7A_D}
          position={[51.91, 0, 57.25]}
        />
        <mesh
          name="Tree_7F_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7F_(2)"].geometry}
          material={materials.Tree_7A_D}
          position={[59.2, 0, -47.6]}
          rotation={[Math.PI, -1.18, Math.PI]}
          scale={1.34}
        />
        <mesh
          name="Tree_7F_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7F_(4)"].geometry}
          material={materials.Tree_7A_D}
          position={[-26, 0, -51.8]}
          rotation={[0, 0.24, 0]}
          scale={1.34}
        />
        <mesh
          name="Tree_7F_(5)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7F_(5)"].geometry}
          material={materials.Tree_7A_D}
          position={[32.7, 0, 57.6]}
          rotation={[0, 0.24, 0]}
          scale={1.07}
        />
        <mesh
          name="Tree_7F_(6)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7F_(6)"].geometry}
          material={materials.Tree_7A_D}
          position={[-49, 0, 80.1]}
          rotation={[Math.PI, -1.41, Math.PI]}
          scale={1.07}
        />
        <mesh
          name="Tree_7C"
          castShadow
          receiveShadow
          geometry={nodes.Tree_7C.geometry}
          material={materials.Tree_7A_D}
          position={[13.15, 0.46, -27.1]}
        />
        <mesh
          name="Tree_7C_(8)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7C_(8)"].geometry}
          material={materials.Tree_7A_D}
          position={[82, 0.46, -24.4]}
          rotation={[-Math.PI, 0.26, -Math.PI]}
          scale={1.28}
        />
        <mesh
          name="Tree_7C_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7C_(1)"].geometry}
          material={materials.Tree_7A_D}
          position={[10.72, 0.46, 20.9]}
          rotation={[-Math.PI, 0.26, -Math.PI]}
        />
        <mesh
          name="Tree_7C_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7C_(2)"].geometry}
          material={materials.Tree_7A_D}
          position={[-5.3, 0.46, -55.1]}
          rotation={[-Math.PI, -0.98, -Math.PI]}
        />
        <mesh
          name="Tree_7C_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7C_(3)"].geometry}
          material={materials.Tree_7A_D}
          position={[-51.5, 0.46, -32]}
          rotation={[-Math.PI, -0.98, -Math.PI]}
        />
        <mesh
          name="Tree_7C_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7C_(4)"].geometry}
          material={materials.Tree_7A_D}
          position={[-61, 0.46, 21.3]}
          rotation={[-Math.PI, -0.98, -Math.PI]}
        />
        <mesh
          name="Tree_7C_(5)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7C_(5)"].geometry}
          material={materials.Tree_7A_D}
          position={[-41.48, 0.46, 74.64]}
          rotation={[-Math.PI, 0.34, -Math.PI]}
          scale={1.48}
        />
        <mesh
          name="Tree_7C_(6)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7C_(6)"].geometry}
          material={materials.Tree_7A_D}
          position={[25.5, 0.46, 52.3]}
          rotation={[-Math.PI, 0.34, -Math.PI]}
          scale={1.14}
        />
        <mesh
          name="Tree_7C_(7)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7C_(7)"].geometry}
          material={materials.Tree_7A_D}
          position={[60, 0.46, 34.7]}
          rotation={[0, 1.2, 0]}
          scale={1.28}
        />
        <mesh
          name="Tree_7G_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7G_(4)"].geometry}
          material={materials.Tree_7A_D}
          position={[-51.2, 0, -19.15]}
          rotation={[Math.PI, -0.88, Math.PI]}
        />
        <mesh
          name="Tree_7G"
          castShadow
          receiveShadow
          geometry={nodes.Tree_7G.geometry}
          material={materials.Tree_7A_D}
          position={[72.92, 0, 48.4]}
        />
        <mesh
          name="Tree_7G_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7G_(1)"].geometry}
          material={materials.Tree_7A_D}
          position={[-59.2, 0, 6.5]}
        />
        <mesh
          name="Tree_7G_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7G_(2)"].geometry}
          material={materials.Tree_7A_D}
          position={[-48.6, 0, 63.5]}
          rotation={[Math.PI, -0.88, Math.PI]}
        />
        <mesh
          name="Tree_7G_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7G_(3)"].geometry}
          material={materials.Tree_7A_D}
          position={[76.2, 0, -40.7]}
          rotation={[Math.PI, -0.88, Math.PI]}
        />
        <mesh
          name="Tree_7G_(5)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7G_(5)"].geometry}
          material={materials.Tree_7A_D}
          position={[8.6, 0, -51.6]}
          rotation={[Math.PI, -0.88, Math.PI]}
          scale={1.2}
        />
        <mesh
          name="Tree_7E"
          castShadow
          receiveShadow
          geometry={nodes.Tree_7E.geometry}
          material={materials.Tree_7A_D}
          position={[12.84, 0, 82.38]}
        />
        <mesh
          name="Tree_7E_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7E_(1)"].geometry}
          material={materials.Tree_7A_D}
          position={[-60.7, 0, 34]}
          rotation={[Math.PI, -1.48, Math.PI]}
          scale={1.12}
        />
        <mesh
          name="Tree_7E_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7E_(2)"].geometry}
          material={materials.Tree_7A_D}
          position={[73.8, 0, 31.5]}
          rotation={[Math.PI, -1.48, Math.PI]}
          scale={1.12}
        />
        <mesh
          name="Tree_7E_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7E_(3)"].geometry}
          material={materials.Tree_7A_D}
          position={[40, 0, -60]}
          rotation={[0, -0.4, 0]}
          scale={1.25}
        />
        <mesh
          name="Tree_7E_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Tree_7E_(4)"].geometry}
          material={materials.Tree_7A_D}
          position={[-18.58, 0, 14.69]}
          rotation={[0, -0.4, 0]}
          scale={0.58}
        />
        <mesh
          name="Barrel_3B_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Barrel_3B_(2)"].geometry}
          material={materials.Props_2A_D}
          position={[-18.35, 0.3, -19.17]}
        />
        <mesh
          name="Barrel_3B_(5)"
          castShadow
          receiveShadow
          geometry={nodes["Barrel_3B_(5)"].geometry}
          material={materials.Props_2A_D}
          position={[-38.74, 0.3, 37.07]}
        />
        <mesh
          name="Barrel_3B_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Barrel_3B_(4)"].geometry}
          material={materials.Props_2A_D}
          position={[56.85, 0.3, 21.24]}
        />
        <mesh
          name="Barrel_3B"
          castShadow
          receiveShadow
          geometry={nodes.Barrel_3B.geometry}
          material={materials.Props_2A_D}
          position={[-39.97, 0.3, 18.94]}
        />
        <mesh
          name="Barrel_3B_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Barrel_3B_(1)"].geometry}
          material={materials.Props_2A_D}
          position={[-34.94, 0.3, -5.17]}
        />
        <mesh
          name="Barrel_3B_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Barrel_3B_(3)"].geometry}
          material={materials.Props_2A_D}
          position={[12.97, 0.3, -16.96]}
        />
        <mesh
          name="Car_18C"
          castShadow
          receiveShadow
          geometry={nodes.Car_18C.geometry}
          material={materials.Car_18C_D}
          position={[-1.5, 0.1, 53]}
          rotation={[0, 1.53, 0]}
        >
          <mesh
            name="Wheel_18C_FL"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_18C_FL.geometry}
            material={materials.Car_18C_D}
            position={[1.03, 0.51, 2.45]}
            rotation={[0, Math.PI / 6, 0]}
          />
          <mesh
            name="Wheel_18C_FR"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_18C_FR.geometry}
            material={materials.Car_18C_D}
            position={[-1.03, 0.51, 2.45]}
            rotation={[0, Math.PI / 6, 0]}
          />
          <mesh
            name="Wheel_18C_RL"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_18C_RL.geometry}
            material={materials.Car_18C_D}
            position={[1.03, 0.51, -1.66]}
          />
          <mesh
            name="Wheel_18C_RR"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_18C_RR.geometry}
            material={materials.Car_18C_D}
            position={[-1.03, 0.51, -1.66]}
          />
        </mesh>
        <mesh
          name="Car_18C_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Car_18C_(3)"].geometry}
          material={materials.Car_18C_D}
          position={[7.5, 0.1, -6]}
          rotation={[0, 1.53, 0]}
        >
          <mesh
            name="Wheel_18C_FL_1"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_18C_FL_1.geometry}
            material={materials.Car_18C_D}
            position={[1.03, 0.51, 2.45]}
            rotation={[0, Math.PI / 6, 0]}
          />
          <mesh
            name="Wheel_18C_FR_1"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_18C_FR_1.geometry}
            material={materials.Car_18C_D}
            position={[-1.03, 0.51, 2.45]}
            rotation={[0, Math.PI / 6, 0]}
          />
          <mesh
            name="Wheel_18C_RL_1"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_18C_RL_1.geometry}
            material={materials.Car_18C_D}
            position={[1.03, 0.51, -1.66]}
          />
          <mesh
            name="Wheel_18C_RR_1"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_18C_RR_1.geometry}
            material={materials.Car_18C_D}
            position={[-1.03, 0.51, -1.66]}
          />
        </mesh>
        <mesh
          name="Car_18C_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Car_18C_(2)"].geometry}
          material={materials.Car_18C_D}
          position={[44, 0.1, -11]}
          rotation={[0, -1.31, 0]}
        >
          <mesh
            name="Wheel_18C_FL_2"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_18C_FL_2.geometry}
            material={materials.Car_18C_D}
            position={[1.03, 0.51, 2.45]}
            rotation={[0, Math.PI / 6, 0]}
          />
          <mesh
            name="Wheel_18C_FR_2"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_18C_FR_2.geometry}
            material={materials.Car_18C_D}
            position={[-1.03, 0.51, 2.45]}
            rotation={[0, Math.PI / 6, 0]}
          />
          <mesh
            name="Wheel_18C_RL_2"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_18C_RL_2.geometry}
            material={materials.Car_18C_D}
            position={[1.03, 0.51, -1.66]}
          />
          <mesh
            name="Wheel_18C_RR_2"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_18C_RR_2.geometry}
            material={materials.Car_18C_D}
            position={[-1.03, 0.51, -1.66]}
          />
        </mesh>
        <mesh
          name="Car_18C_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Car_18C_(1)"].geometry}
          material={materials.Car_18C_D}
          position={[0.5, 0.1, -16]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="Wheel_18C_FL_3"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_18C_FL_3.geometry}
            material={materials.Car_18C_D}
            position={[1.03, 0.51, 2.45]}
            rotation={[0, Math.PI / 6, 0]}
          />
          <mesh
            name="Wheel_18C_FR_3"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_18C_FR_3.geometry}
            material={materials.Car_18C_D}
            position={[-1.03, 0.51, 2.45]}
            rotation={[0, Math.PI / 6, 0]}
          />
          <mesh
            name="Wheel_18C_RL_3"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_18C_RL_3.geometry}
            material={materials.Car_18C_D}
            position={[1.03, 0.51, -1.66]}
          />
          <mesh
            name="Wheel_18C_RR_3"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_18C_RR_3.geometry}
            material={materials.Car_18C_D}
            position={[-1.03, 0.51, -1.66]}
          />
        </mesh>
        <mesh
          name="Car_14I"
          castShadow
          receiveShadow
          geometry={nodes.Car_14I.geometry}
          material={materials.Car_14I_D}
          position={[25, 0.1, 37]}
          rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
        >
          <mesh
            name="Wheel_14I_FL"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_14I_FL.geometry}
            material={materials.Car_14I_D}
            position={[1.07, 0.42, 1.59]}
          />
          <mesh
            name="Wheel_14I_FR"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_14I_FR.geometry}
            material={materials.Car_14I_D}
            position={[-1.07, 0.42, 1.59]}
          />
          <mesh
            name="Wheel_14I_RL"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_14I_RL.geometry}
            material={materials.Car_14I_D}
            position={[1.1, 0.42, -1.38]}
          />
          <mesh
            name="Wheel_14I_RR"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_14I_RR.geometry}
            material={materials.Car_14I_D}
            position={[-1.1, 0.42, -1.38]}
          />
        </mesh>
        <mesh
          name="Car_14I_(4)"
          castShadow
          receiveShadow
          geometry={nodes["Car_14I_(4)"].geometry}
          material={materials.Car_14I_D}
          position={[-36, 0.1, 13]}
        >
          <mesh
            name="Wheel_14I_FL_1"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_14I_FL_1.geometry}
            material={materials.Car_14I_D}
            position={[1.07, 0.42, 1.59]}
          />
          <mesh
            name="Wheel_14I_FR_1"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_14I_FR_1.geometry}
            material={materials.Car_14I_D}
            position={[-1.07, 0.42, 1.59]}
          />
          <mesh
            name="Wheel_14I_RL_1"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_14I_RL_1.geometry}
            material={materials.Car_14I_D}
            position={[1.1, 0.42, -1.38]}
          />
          <mesh
            name="Wheel_14I_RR_1"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_14I_RR_1.geometry}
            material={materials.Car_14I_D}
            position={[-1.1, 0.42, -1.38]}
          />
        </mesh>
        <mesh
          name="Car_14I_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Car_14I_(2)"].geometry}
          material={materials.Car_14I_D}
          position={[41, 0.1, 11]}
        >
          <mesh
            name="Wheel_14I_FL_2"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_14I_FL_2.geometry}
            material={materials.Car_14I_D}
            position={[1.07, 0.42, 1.59]}
          />
          <mesh
            name="Wheel_14I_FR_2"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_14I_FR_2.geometry}
            material={materials.Car_14I_D}
            position={[-1.07, 0.42, 1.59]}
          />
          <mesh
            name="Wheel_14I_RL_2"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_14I_RL_2.geometry}
            material={materials.Car_14I_D}
            position={[1.1, 0.42, -1.38]}
          />
          <mesh
            name="Wheel_14I_RR_2"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_14I_RR_2.geometry}
            material={materials.Car_14I_D}
            position={[-1.1, 0.42, -1.38]}
          />
        </mesh>
        <mesh
          name="Car_14I_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Car_14I_(1)"].geometry}
          material={materials.Car_14I_D}
          position={[-15, 0.1, -12]}
          rotation={[0, -Math.PI / 6, 0]}
        >
          <mesh
            name="Wheel_14I_FL_3"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_14I_FL_3.geometry}
            material={materials.Car_14I_D}
            position={[1.07, 0.42, 1.59]}
            rotation={[0, -Math.PI / 6, 0]}
          />
          <mesh
            name="Wheel_14I_FR_3"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_14I_FR_3.geometry}
            material={materials.Car_14I_D}
            position={[-1.07, 0.42, 1.59]}
            rotation={[0, -Math.PI / 6, 0]}
          />
          <mesh
            name="Wheel_14I_RL_3"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_14I_RL_3.geometry}
            material={materials.Car_14I_D}
            position={[1.1, 0.42, -1.38]}
          />
          <mesh
            name="Wheel_14I_RR_3"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_14I_RR_3.geometry}
            material={materials.Car_14I_D}
            position={[-1.1, 0.42, -1.38]}
          />
        </mesh>
        <mesh
          name="Gas_Station_2A"
          castShadow
          receiveShadow
          geometry={nodes.Gas_Station_2A.geometry}
          material={materials.Gas_Station_1A_D}
          position={[-5, 0, -20]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="Gas_Station_2A_Rotating_Logo"
            castShadow
            receiveShadow
            geometry={nodes.Gas_Station_2A_Rotating_Logo.geometry}
            material={materials.Gas_Station_1A_D}
            position={[18, 0, 0]}
          />
          <mesh
            name="Gas_Station_2A_D_Addon"
            castShadow
            receiveShadow
            geometry={nodes.Gas_Station_2A_D_Addon.geometry}
            material={materials.Road_1A_D}
            position={[12, 0, 0]}
          />
          <mesh
            name="Gas_Station_2A_Window_Lights"
            castShadow
            receiveShadow
            geometry={nodes.Gas_Station_2A_Window_Lights.geometry}
            material={materials.Windows}
          />
        </mesh>
        <mesh
          name="Building_17E"
          castShadow
          receiveShadow
          geometry={nodes.Building_17E.geometry}
          material={materials.Gas_Station_1A_D}
          position={[-29, 0, 54]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <mesh
            name="Building_17E_Logo"
            castShadow
            receiveShadow
            geometry={nodes.Building_17E_Logo.geometry}
            material={materials.Road_1A_D}
            rotation={[0, Math.PI / 2, 0]}
          />
        </mesh>
        <mesh
          name="Building_17E_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Building_17E_(1)"].geometry}
          material={materials.Gas_Station_1A_D}
          position={[25, 0, -42]}
        >
          <mesh
            name="Building_17E_Logo_1"
            castShadow
            receiveShadow
            geometry={nodes.Building_17E_Logo_1.geometry}
            material={materials.Road_1A_D}
            rotation={[0, Math.PI / 2, 0]}
          />
        </mesh>
        <mesh
          name="Building_17E_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Building_17E_(2)"].geometry}
          material={materials.Gas_Station_1A_D}
          position={[60, 0, -9]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="Building_17E_Logo_2"
            castShadow
            receiveShadow
            geometry={nodes.Building_17E_Logo_2.geometry}
            material={materials.Road_1A_D}
            rotation={[0, Math.PI / 2, 0]}
          />
        </mesh>
        <mesh
          name="Gas_Pump_1A_(12)"
          castShadow
          receiveShadow
          geometry={nodes["Gas_Pump_1A_(12)"].geometry}
          material={materials.Gas_Station_1A_D}
          position={[35, 0, -28]}
          rotation={[Math.PI, -0.79, Math.PI]}
        />
        <mesh
          name="Gas_Pump_1A_(7)"
          castShadow
          receiveShadow
          geometry={nodes["Gas_Pump_1A_(7)"].geometry}
          material={materials.Gas_Station_1A_D}
          position={[-37, 0, 19]}
          rotation={[0, 0.79, 0]}
        />
        <mesh
          name="Gas_Pump_1A_(11)"
          castShadow
          receiveShadow
          geometry={nodes["Gas_Pump_1A_(11)"].geometry}
          material={materials.Gas_Station_1A_D}
          position={[35, 0, -33]}
          rotation={[Math.PI, -0.79, Math.PI]}
        />
        <mesh
          name="Gas_Pump_1A_(9)"
          castShadow
          receiveShadow
          geometry={nodes["Gas_Pump_1A_(9)"].geometry}
          material={materials.Gas_Station_1A_D}
          position={[17, 0, -33]}
          rotation={[0, -0.79, 0]}
        />
        <mesh
          name="Gas_Pump_1A_(8)"
          castShadow
          receiveShadow
          geometry={nodes["Gas_Pump_1A_(8)"].geometry}
          material={materials.Gas_Station_1A_D}
          position={[-37, 0, 3]}
          rotation={[0, -0.79, 0]}
        />
        <mesh
          name="Gas_Pump_1A_(10)"
          castShadow
          receiveShadow
          geometry={nodes["Gas_Pump_1A_(10)"].geometry}
          material={materials.Gas_Station_1A_D}
          position={[17, 0, -28]}
          rotation={[0, -0.79, 0]}
        />
        <mesh
          name="Gas_Pump_1A_(6)"
          castShadow
          receiveShadow
          geometry={nodes["Gas_Pump_1A_(6)"].geometry}
          material={materials.Gas_Station_1A_D}
          position={[-5, 0, -14]}
          rotation={[0, 0.79, 0]}
        />
        <mesh
          name="Gas_Tank_2A"
          castShadow
          receiveShadow
          geometry={nodes.Gas_Tank_2A.geometry}
          material={materials.Gas_Station_1A_D}
          position={[-46, 0, 24]}
          rotation={[0, Math.PI / 3, 0]}
        />
        <mesh
          name="Gas_Tank_2A_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Gas_Tank_2A_(1)"].geometry}
          material={materials.Gas_Station_1A_D}
          position={[-46, 0, 28]}
          rotation={[-Math.PI, Math.PI / 6, -Math.PI]}
        />
        <mesh
          name="Gas_Station_1A"
          castShadow
          receiveShadow
          geometry={nodes.Gas_Station_1A.geometry}
          material={materials.Gas_Station_1A_D}
          position={[-42, 0, 11]}
        >
          <mesh
            name="Gas_Station_1A_Rotating_Text"
            castShadow
            receiveShadow
            geometry={nodes.Gas_Station_1A_Rotating_Text.geometry}
            material={materials.Gas_Station_1A_D}
            position={[18, 0, 0]}
          />
          <mesh
            name="Gas_Station_1A_D_Addon"
            castShadow
            receiveShadow
            geometry={nodes.Gas_Station_1A_D_Addon.geometry}
            material={materials.Road_1A_D}
          />
          <mesh
            name="Gas_Station_1A_Window_Lights"
            castShadow
            receiveShadow
            geometry={nodes.Gas_Station_1A_Window_Lights.geometry}
            material={materials.Windows}
          />
        </mesh>
        <mesh
          name="Gas_Tank_1A_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Gas_Tank_1A_(1)"].geometry}
          material={materials.Gas_Station_1A_D}
          position={[-56, 0, -9]}
          rotation={[Math.PI, -Math.PI / 4, Math.PI]}
        />
        <mesh
          name="Gas_Tank_1B"
          castShadow
          receiveShadow
          geometry={nodes.Gas_Tank_1B.geometry}
          material={materials.Gas_Station_1A_D}
          position={[-56, 0, -3]}
          rotation={[Math.PI, -Math.PI / 4, Math.PI]}
        />
        <mesh
          name="Car_6G_(3)"
          castShadow
          receiveShadow
          geometry={nodes["Car_6G_(3)"].geometry}
          material={materials.Car_6G_D}
          position={[-32, 0.1, 21]}
        >
          <mesh
            name="Wheel_6G_FL"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_6G_FL.geometry}
            material={materials.Car_6G_D}
            position={[1.07, 0.42, 1.45]}
          />
          <mesh
            name="Wheel_6G_FR"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_6G_FR.geometry}
            material={materials.Car_6G_D}
            position={[-1.07, 0.42, 1.45]}
          />
          <mesh
            name="Wheel_6G_RL"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_6G_RL.geometry}
            material={materials.Car_6G_D}
            position={[1.07, 0.42, -1.52]}
          />
          <mesh
            name="Wheel_6G_RR"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_6G_RR.geometry}
            material={materials.Car_6G_D}
            position={[-1.07, 0.42, -1.52]}
          />
        </mesh>
        <mesh
          name="Car_6G_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Car_6G_(2)"].geometry}
          material={materials.Car_6G_D}
          position={[49, 0.1, 25]}
          rotation={[Math.PI, 0, Math.PI]}
        >
          <mesh
            name="Wheel_6G_FL_1"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_6G_FL_1.geometry}
            material={materials.Car_6G_D}
            position={[1.07, 0.42, 1.45]}
          />
          <mesh
            name="Wheel_6G_FR_1"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_6G_FR_1.geometry}
            material={materials.Car_6G_D}
            position={[-1.07, 0.42, 1.45]}
          />
          <mesh
            name="Wheel_6G_RL_1"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_6G_RL_1.geometry}
            material={materials.Car_6G_D}
            position={[1.07, 0.42, -1.52]}
          />
          <mesh
            name="Wheel_6G_RR_1"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_6G_RR_1.geometry}
            material={materials.Car_6G_D}
            position={[-1.07, 0.42, -1.52]}
          />
        </mesh>
        <mesh
          name="Car_6G_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Car_6G_(1)"].geometry}
          material={materials.Car_6G_D}
          position={[20.24, 0.1, -13.23]}
          rotation={[0, -Math.PI / 4, 0]}
        >
          <mesh
            name="Wheel_6G_FL_2"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_6G_FL_2.geometry}
            material={materials.Car_6G_D}
            position={[1.07, 0.42, 1.45]}
          />
          <mesh
            name="Wheel_6G_FR_2"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_6G_FR_2.geometry}
            material={materials.Car_6G_D}
            position={[-1.07, 0.42, 1.45]}
          />
          <mesh
            name="Wheel_6G_RL_2"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_6G_RL_2.geometry}
            material={materials.Car_6G_D}
            position={[1.07, 0.42, -1.52]}
          />
          <mesh
            name="Wheel_6G_RR_2"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_6G_RR_2.geometry}
            material={materials.Car_6G_D}
            position={[-1.07, 0.42, -1.52]}
          />
        </mesh>
        <mesh
          name="Car_6G"
          castShadow
          receiveShadow
          geometry={nodes.Car_6G.geometry}
          material={materials.Car_6G_D}
          position={[13, 0.1, 45]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="Wheel_6G_FL_3"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_6G_FL_3.geometry}
            material={materials.Car_6G_D}
            position={[1.07, 0.42, 1.45]}
          />
          <mesh
            name="Wheel_6G_FR_3"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_6G_FR_3.geometry}
            material={materials.Car_6G_D}
            position={[-1.07, 0.42, 1.45]}
          />
          <mesh
            name="Wheel_6G_RL_3"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_6G_RL_3.geometry}
            material={materials.Car_6G_D}
            position={[1.07, 0.42, -1.52]}
          />
          <mesh
            name="Wheel_6G_RR_3"
            castShadow
            receiveShadow
            geometry={nodes.Wheel_6G_RR_3.geometry}
            material={materials.Car_6G_D}
            position={[-1.07, 0.42, -1.52]}
          />
        </mesh>
        <mesh
          name="Building_7C"
          castShadow
          receiveShadow
          geometry={nodes.Building_7C.geometry}
          material={materials.Building_7B_D}
          position={[-47, 0, 40]}
          rotation={[-Math.PI, 0, -Math.PI]}
        >
          <mesh
            name="Building_7C_Logo"
            castShadow
            receiveShadow
            geometry={nodes.Building_7C_Logo.geometry}
            material={materials.Road_1A_D}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            name="Building_7C_Window_Lights"
            castShadow
            receiveShadow
            geometry={nodes.Building_7C_Window_Lights.geometry}
            material={materials.Windows}
          />
        </mesh>
        <mesh
          name="Building_7C_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Building_7C_(1)"].geometry}
          material={materials.Building_7B_D}
          position={[46, 0, -25]}
        >
          <mesh
            name="Building_7C_Logo_1"
            castShadow
            receiveShadow
            geometry={nodes.Building_7C_Logo_1.geometry}
            material={materials.Road_1A_D}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            name="Building_7C_Window_Lights_1"
            castShadow
            receiveShadow
            geometry={nodes.Building_7C_Window_Lights_1.geometry}
            material={materials.Windows}
          />
        </mesh>
        <mesh
          name="Building_7C_(2)"
          castShadow
          receiveShadow
          geometry={nodes["Building_7C_(2)"].geometry}
          material={materials.Building_7B_D}
          position={[9, 0, -40]}
        >
          <mesh
            name="Building_7C_Logo_2"
            castShadow
            receiveShadow
            geometry={nodes.Building_7C_Logo_2.geometry}
            material={materials.Road_1A_D}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            name="Building_7C_Window_Lights_2"
            castShadow
            receiveShadow
            geometry={nodes.Building_7C_Window_Lights_2.geometry}
            material={materials.Windows}
          />
        </mesh>
        <mesh
          name="Building_7B"
          castShadow
          receiveShadow
          geometry={nodes.Building_7B.geometry}
          material={materials.Building_7B_D}
          position={[-24, 0, -20]}
          rotation={[0, Math.PI / 2, 0]}
        >
          <mesh
            name="Building_7B_Window_Lights"
            castShadow
            receiveShadow
            geometry={nodes.Building_7B_Window_Lights.geometry}
            material={materials.Windows}
          />
        </mesh>
        <mesh
          name="Building_7B_(1)"
          castShadow
          receiveShadow
          geometry={nodes["Building_7B_(1)"].geometry}
          material={materials.Building_7B_D}
          position={[-36, 0, -20]}
        >
          <mesh
            name="Building_7B_Window_Lights_1"
            castShadow
            receiveShadow
            geometry={nodes.Building_7B_Window_Lights_1.geometry}
            material={materials.Windows}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("./models/Demo_Scene_1.glb");
