/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Yol(props) {
  const { nodes, materials } = useGLTF("./models/Yol.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-2.2, -0.08, -38]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, 38]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_1.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, -22]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_2.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, -46]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_3.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, -2]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_4.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, -2]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_5.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, -14]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_6.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, 46]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_7.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, -10]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_8.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, 42]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_9.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, 22]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_10.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, 42]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_11.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, -26]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_12.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, 10]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_13.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, -34]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_14.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, -46]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_15.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, 26]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_16.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, -18]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_17.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, -6]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_18.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, 34]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_19.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, 14]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_20.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, 30]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_21.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, -42]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_22.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, 22]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_23.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, -42]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_24.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, -10]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_25.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, 14]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_26.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, -6]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_27.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, -26]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_28.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, 30]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_29.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, -38]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_30.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, -22]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_31.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, 2]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_32.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, -30]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_33.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, 34]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_34.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, -18]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_35.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, 2]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_36.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, 18]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_37.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, 46]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_38.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, 10]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_39.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, 6]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_40.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, -34]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_41.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, -14]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_42.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, 38]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_43.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, 26]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_44.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[-2.2, -0.08, 6]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_45.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, 18]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_46.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
      <group position={[1.8, -0.08, -30]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.street_47.geometry}
          material={materials["street 3"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[200, 200, 100]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/Yol.glb");
